apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning
  labels:
    {{- include "learning.labels" . | nindent 4}}
    app.kubernetes.io/component: learning
spec:
  replicas: {{ .Values.learning.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: learning
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: learning
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: learning
          image: {{ .Values.learning.image }}
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: learning_db_url
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000
