apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "learning.labels" . | nindent 4}}
type: Opaque
data:
  learning_db_url: {{ .Values.learningMongoUrl | b64enc }}